name: Build & Publish Docker Image
on:
  release:
    types: [published]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
          scopes: write:packages

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          #tags: ${{ steps.metadata.outputs.tags }}
          tags: ghcr.io/${{ github.repository }}/nodejs:5.5
          labels: ${{ steps.metadata.outputs.labels }}